test: 99999
spring:
  config:
    import: classpath:/application-prod.properties

  # https://www.cockroachlabs.com/blog/tutorial-spring-hibernate/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9999/postgres
    username: sodevuser
    password: sodevuserpw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect